Automation: 
  name: 'Automation'
  action-bar: ''
  prefix: '&6Automation'
  group: 'class'
  mana: '&2Mana'
  max-level: 255
  parent: 'Citizen'
  needs-permission: 'false'
  attributes: 
    health-base: '20'
    health-scale: '0'
    mana-base: '20'
    mana-scale: '0'
    directdmg-base: '1'
    directdmg-scale: '1'
    directdef-base: '1'
    directdef-scale: '1'
    vitality-base: '22'
    vitality-scale: '1.15'
    spirit-base: '22'
    spirit-scale: '1.15'
    aquatia-base: '0'
    aquatia-scale: '0'
    strength-base: '10'
    strength-scale: '1'
    intelligence-base: '20'
    intelligence-scale: '1.05'
    endurance-base: '15'
    endurance-scale: '0'
    willpower-base: '25'
    willpower-scale: '0'
    agility-base: '0'
    agility-scale: '0'
    dice-base: '0'
    dice-scale: '0'
    xpbonus-base: '0'
    xpbonus-scale: '0'
    firedmg-base: '0'
    firedmg-scale: '0'
    waterdmg-base: '0'
    waterdmg-scale: '0'
    lightdmg-base: '0'
    lightdmg-scale: '0'
    earthdmg-base: '0'
    earthdmg-scale: '0'
    thunderdmg-base: '0'
    thunderdmg-scale: '0'
    winddmg-base: '0'
    winddmg-scale: '0'
    darkdmg-base: '0'
    darkdmg-scale: '0'
    neutraldmg-base: '0'
    neutraldmg-scale: '0'
    physicaldmg-base: '0'
    physicaldmg-scale: '0'
    firedef-base: '0'
    firedef-scale: '0'
    waterdef-base: '0'
    waterdef-scale: '0'
    lightdef-base: '0'
    lightdef-scale: '0'
    earthdef-base: '0'
    earthdef-scale: '0'
    thunderdef-base: '0'
    thunderdef-scale: '0'
    winddef-base: '0'
    winddef-scale: '0'
    darkdef-base: '0'
    darkdef-scale: '0'
    neutraldef-base: '0'
    neutraldef-scale: '0'
    physicaldef-base: '0'
    physicaldef-scale: '0'
    basespeed-base: '4'
    basespeed-scale: '0'
    a_level-base: '1'
    a_level-scale: '1'
    staminabonus-base: '100'
    staminabonus-scale: '0'
    staminabonusminusone-base: '99'
    staminabonusminusone-scale: '0'
  mana-regen: 1.0
  tree: 'FLOOD'
  blacklist:  []
  skills: 
  - 'Light Combo Automation'
  - 'Heavy Combo Automation'
  - 'Thruster Uppercut'
  - 'Forcefield'
  - 'Missile'
  - 'Flamethrower'
  - 'Nano-Repair'
  - 'Rapid Blast'
  - 'Power Shot'
  - 'Surging Shield'
  - 'Overdrive'
  - 'Self-Destruct'
  - 'Electric Fence'
  - 'Electric Net'
  - 'EMP Blast'
  - 'External Hull'
  - 'Auto-Repair'
  - 'Metal Body'
  - 'Alby-Automation'
  - 'Xync-Automation'
  - 'Yryn-Automation'
  - 'Nrik-Automation'
  - 'Araw-Automation'
  - 'Redirect Systems'
  icon: 'ARMOR_STAND'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&dAutomation'
  exp-source: 511
