Araw-Automation: 
  name: 'Araw-Automation'
  type: 'Rune'
  max-level: 3
  skill-req-lvl: 1
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '0'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'IRON_BLOCK'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&d{name}'
  - ''
  - '&eSetting for your Araw Rune Option. (&90 for Vanilla&e)'
  - '&eLeft click to increase, Right Click to Decrease.'
  - '&aCurrent Mode: &b[{level}]'
  - ''
  - '&dMode 1: &cRocket Dash'
  - '&6Skill Addon; &9+Replacement, &e3s Cooldown'
  - '&7Replaces the “L” combo into a dash'
  - '&7attack. Deals repeated damage, good'
  - '&7knockback, and brief invincibility.'
  - ''
  - '&dMode 2: &cGround Smash'
  - '&6Skill Addon; &9+Replacement, &e3s Cooldown'
  - '&7Replaces the “L” combo into a smashing'
  - '&7ground attack. Deals AOE damage, and knockback.'
  - ''
  - '&dMode 3: &cUppercut Counter'
  - '&6Skill Addon; &9+Replacement, &e3s Cooldown'
  - '&7Replaces the “L” combo into an uppercut attack'
  - '&7that sends up to 3 targets flying away.'
  desc:  []
  components: 
    Initialize: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Value Set-b: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            key: 'value'
            value-base: '1'
            value-scale: '0'
            indicator: '2D'
          children:  {}
